# Site settings
title:       Fixpoint
email:       eytchu@gmail.com
author:      Eric Chu
description: "A collection of technical notes"
baseurl:     ""
url:         "http://echu.github.io"
date_format: "%b %-d, %Y"

# Google services
google_analytics: "UA-68317194-1"
google_verification:

# Optional features
mathjax:              true
animated:             true
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:        echu
bitbucket_username:
stackoverflow_id:
twitter_username:       eytchu
google_plus_id:
linkedin_username:      eytchu
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
